# Generated by Django 5.0.4 on 2024-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000000)),
            ],
        ),
    ]
